<a href="https://colab.research.google.com/github/Raghad-ibrahim-alshiban/mawhiba-/blob/main/Copy_of_Untitled2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
thirdRow=arr[2]
print(thirdRow)

[ 9 10 11 12]


In [ ]:
thirdColumn=arr[:,2]
print(thirdColumn)

[ 3  7 11]


In [ ]:
subset=arr[:2,-2:]
print(subset)

[[3 4]
 [7 8]]


In [ ]:
reshaped_arr = arr.reshape(6, 2)
print(reshaped_arr)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [ ]:
arr1 = np.array([[5, 4, 3],
                [2, 1, 1],
                [3, 5, 1],
                [2, 4, 5]])

print("المصفوفة:")
print(arr)

المصفوفة:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
rows, cols = arr1.shape
print(f"عدد الصفوف: {rows}, عدد الأعمدة: {cols}")

عدد الصفوف: 4, عدد الأعمدة: 3


In [ ]:
print("المصفوفة A:")
print(arr1[:,2])

المصفوفة A:
[3 1 1 5]


In [ ]:
print("المصفوفة B:")
print(arr1[1:3, 0:3])

المصفوفة B:
[[2 1 1]
 [3 5 1]]


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
print("المصفوفة C:")
print(arr1[1:3, 0:2])

المصفوفة C:
[[2 1]
 [3 5]]
